import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: users, isLoading } = trpc.useQuery(["user.all"]);
  const { data: user } = trpc.useQuery(["user.byId", 1]);
  console.log("data", users, isLoading);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          tRPC with <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <ul>
          {users?.map((user) => (
            <li key={user.id}>
              {user.id} - {user.name} - {user.createdAt.toDateString()}
            </li>
          ))}
        </ul>
        User: {JSON.stringify(user)}
      </main>
    </div>
  );
};

export default Home;
